# Generated by Django 3.1.7 on 2021-04-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('mbti_id', models.AutoField(primary_key=True, serialize=False)),
                ('mbti_type', models.CharField(max_length=10)),
                ('mbti_desc', models.TextField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='MBTIBook',
            fields=[
                ('mbti_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.CharField(max_length=45)),
                ('mbti_id', models.IntegerField()),
            ],
        ),
    ]
