# Generated by Django 3.1.7 on 2021-04-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbtis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtibook',
            name='book_id',
            field=models.CharField(max_length=45),
        ),
    ]
