# Generated by Django 3.1.7 on 2021-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=60)),
                ('book_author', models.CharField(max_length=45)),
                ('book_publisher', models.CharField(max_length=60)),
                ('book_desc', models.TextField(blank=True, null=True)),
                ('category_id', models.IntegerField()),
                ('book_category', models.CharField(max_length=45)),
                ('book_images', models.IntegerField(blank=True, null=True)),
                ('book_pages', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=60)),
                ('report_content', models.TextField(max_length=1000)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('review_rating', models.IntegerField()),
                ('review_content', models.TextField(max_length=200)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
