# Generated by Django 3.1.7 on 2021-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookscategory',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book_id',
        ),
        migrations.AddField(
            model_name='bookscategory',
            name='book_isbn',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='book_isbn',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='book_isbn',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
