# Generated by Django 3.1.7 on 2021-03-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksMaincategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'books_maincategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksSubcategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('main', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books_subcategory',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
    ]
