# Generated by Django 3.1.7 on 2021-04-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210405_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pubdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_publisher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='book_name',
            field=models.CharField(max_length=100),
        ),
    ]
