# Generated by Django 3.1.7 on 2021-04-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210407_2131'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_isbn'], name='books_book_book_is_58fb9a_idx'),
        ),
    ]
