# Generated by Django 3.1.7 on 2021-04-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbtis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbtibook',
            old_name='book_id',
            new_name='book_isbn',
        ),
    ]
