# Generated by Django 3.1.7 on 2021-04-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestseller',
            old_name='best_seller_id',
            new_name='bestseller_id',
        ),
    ]
