# Generated by Django 3.1.7 on 2021-04-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0003_auto_20210407_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentRecommendBook',
        ),
    ]
