# Generated by Django 3.1.7 on 2021-03-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210326_1048'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books_book',
        ),
    ]
