# Generated by Django 3.1.7 on 2021-04-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeRecommendBook',
            fields=[
                ('collaborative_recommend_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('book_isbn', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ContentRecommendBook',
            fields=[
                ('content_recommend_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('book_isbn', models.CharField(max_length=45)),
            ],
        ),
    ]
