# Generated by Django 3.1.7 on 2021-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('best_seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_isbn', models.CharField(max_length=45)),
                ('book_title', models.CharField(max_length=60)),
                ('book_author', models.CharField(max_length=45)),
                ('book_publisher', models.CharField(max_length=60)),
                ('book_pubdate', models.CharField(blank=True, max_length=60, null=True)),
                ('book_pages', models.IntegerField(blank=True, null=True)),
                ('book_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
