# Generated by Django 3.1.7 on 2021-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0002_auto_20210406_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGenderRecommendBook',
            fields=[
                ('agegender_recommend_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('book_isbn', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'recommends_age_gender',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContentsBasedBooks',
            fields=[
                ('contents_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_isbn', models.CharField(max_length=45)),
                ('relative_isbn1', models.CharField(max_length=45)),
                ('relative_isbn2', models.CharField(max_length=45)),
                ('relative_isbn3', models.CharField(max_length=45)),
                ('relative_isbn4', models.CharField(max_length=45)),
                ('relative_isbn5', models.CharField(max_length=45)),
                ('relative_isbn6', models.CharField(max_length=45)),
                ('relative_isbn7', models.CharField(max_length=45)),
                ('relative_isbn8', models.CharField(max_length=45)),
                ('relative_isbn9', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'recommends_content',
                'managed': True,
            },
        ),
    ]
