# Generated by Django 3.1.7 on 2021-04-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210405_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dibs',
            options={'managed': False},
        ),
    ]
