# Generated by Django 3.1.7 on 2021-03-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210323_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dibs',
            options={'managed': False},
        ),
    ]
