# Generated by Django 3.1.7 on 2021-03-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210323_1603'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dibs',
            table='accounts_dibs',
        ),
    ]
