# Generated by Django 3.1.7 on 2021-04-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210324_1123'),
        ('accounts', '0007_auto_20210325_1413'),
    ]

    operations = [
    ]
